### ISSUE TITLE
/pages/={path} request query params are not parsed correctly

### ISSUE THREAD

**Issue by modethirteen** [MindTouch/DekiChromeProfiler#6]
Request contains: &redirects=0&include=contents,prevnext
Extension redirects to: &redirects=0,prevnext

![screen shot 2013-06-20 at 9 17 41 pm](https://f.cloud.github.com/assets/45862/685381/f7f93a64-da29-11e2-9305-0230c39e45cd.png)

**Comment by yurigorokhov** [comment]
@modethirteen is this still an issue do you know?
